language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install -o --no-interaction

script:
 - phpunit -c test/Unit/phpunit.xml test/Unit/

after_script:
 - php vendor/bin/coveralls -v
